### ISSUE TITLE
variable : Tensor = ...

### ISSUE THREAD

**Issue by QiangAIResearcher** [ManifoldFR/point-process-nets#2]
Hi,

Thank you very much for sharing the codes.

One problem: the python complier complains an SyntaxError of invalid syntax in the line 124, h_t : Tensor = hidden * torch.exp(-decay * dt). Could you please be so kind to explain why you insert the ": Tensor" between the new variable h_t and the equation symbol? Many thank!

**Comment by ManifoldFR** [comment]
Hello! Sorry for the late reply, I didn't activate the notifications on GitHub. They're syntax for type annotations from a recent version of Python -- 3.7+ I think. I used them to get method/attribute hints to show up faster inside of PyCharm.
