### ISSUE TITLE
data files cannot be downloaded with Git LFS

### ISSUE THREAD

**Issue by moshen80** [ManifoldFR/point-process-nets#3]
Hi,

I have been trying to clone and test this repository, but the pickle files cannot be downloaded when I clone the repos, and I'll get the error that files don't exist on the server.

it'd be highly appreciated if you can help me with this issue and if it's not too much too ask upload the data files on the cloud where I can download them.

Thanks

**Comment by ManifoldFR** [comment]
Hi, sorry about that, it seems I never checked that Git LFS pushed to GitHub -- this repo is a mirror of the initial repo which is here: https://gitlab.binets.fr/wilson.jallet/map511-p3a

**Comment by ManifoldFR** [comment]
I just checked out the references from the original repo and re-pushed them to this repo -- now the LFS files should work.
